sudo: required
dist: xenial
language: c++
env:
    global:
        - CMAKE_PREFIX = $HOME/prebuilt/cmake
        - CMAKE_BIN = $CMAKE_PREFIX/bin/cmake
        - CMAKE_LINUX_URL==https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.sh ;

notifications:
    slack: depthmapx:B3CKNlNDLrNz1vSOU5yoQQqA


before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.3-xenial
  - sudo add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt5113d qt511tools libgl1-mesa-dev libglu1-mesa-dev python3.5
  - if [ ! -e "$CMAKE_BIN" ]; then

            mkdir -p "$CMAKE_PREFIX";

            curl --insecure -L "$CMAKE_LINUX_URL" -o cmake-linux.sh ;

            bash cmake-linux.sh --skip-license --prefix=$CMAKE_PREFIX ;

    fi

script:
  - source /opt/qt511/bin/qt511-env.sh
  - mkdir build && cd build
  - $CMAKE_BIN -DCMAKE_BUILD_TYPE=Release ..
  - make
  - ./cliTest/cliTest && ./GuiUnitTest/GuiUnitTest && ./salaTest/salaTest && ./genlibTest/genlibTest
  - cd ../RegressionTest/test && python3.5 test_main.py && cd .. && python3.5 RegressionTestRunner.py && python3.5 RegressionTestRunner.py regressionconfig_agents.json


cache:
    apt: true
    ccache: true
    directories:
    - $CMAKE_PREFIX
