sudo: required
dist: xenial
language: c++
service: docker
env:
    global:
        - CMAKE_PREFIX=$HOME/prebuilt/cmake
        - CMAKE_BIN=$CMAKE_PREFIX/bin/cmake
        - CMAKE_LINUX_URL=https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.sh ;
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
 
notifications:
    slack: depthmapx:B3CKNlNDLrNz1vSOU5yoQQqA


script:
  - docker run -v .:/mnt/code blackseamonster:depthmapx-buildenv:0.3 bash -c ci/build.sh
  - make
  - ./cliTest/cliTest && ./GuiUnitTest/GuiUnitTest && ./salaTest/salaTest && ./genlibTest/genlibTest
  - cd ../RegressionTest/test && python3.5 test_main.py && cd .. && python3.5 RegressionTestRunner.py && python3.5 RegressionTestRunner.py regressionconfig_agents.json

