sudo: required
dist: xenial
language: c++
notifications:
    slack: depthmapx:B3CKNlNDLrNz1vSOU5yoQQqA


before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.3-xenial
  - sudo add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo add-apt-repository --yes ppa:andrew-fuller/cmake
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt5113d qt511tools libgl1-mesa-dev libglu1-mesa-dev python3.5 cmake
  - cmake --version

script:
  - source /opt/qt511/bin/qt511-env.sh
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - ./cliTest/cliTest && ./GuiUnitTest/GuiUnitTest && ./salaTest/salaTest && ./genlibTest/genlibTest
  - cd ../RegressionTest/test && python3.5 test_main.py && cd .. && python3.5 RegressionTestRunner.py && python3.5 RegressionTestRunner.py regressionconfig_agents.json
